lib/index.js
test/jwt.test.js

I use the express-jwt middleware on all my routes, some routes are public and some are private. So I use ```  credentialsRequired: false``` and in another middleware I limit the access by looking at the ```req.user``` object.
But I noticed that if the user supplies a invalid or expired token the credentialsRequired flag is not being used and the user is blocked access even if that particular route was supposed to be public.

Should not throw exception with invalid token if credentials are not required

---

README.md

Adds in missing word to fix grammar.
BEFORE: "JWTs are typically used protect API endpoints"
AFTER: "JWTs are typically used to protect API endpoints"

Update README.md adds in missing word

---

lib/index.js

I found this was a problem when dealing with JWT.  Some clients were submitting with a scheme named something other than Bearer.  I made this change so that the error message showed what was true.  Without this change, the module acts as if there isn't a token being submitted which is incorrect.  Please pull this into main branch.

Add Additional Error Handling for Format/Scheme

---

lib/index.js
test/jwt.test.js

It appears that since the new multitenancy callback features have gone in, you cannot use the middleware if you provide a secret in the form of a `Buffer`.
This is due to the fact that the code is checking to see if the `secret` is static by checking if it is a string. If so, it is wrapped in a callback function. This is fine unless your `secret` is a `Buffer` in which case it must also be wrapped.
This PR also contains a test which demonstrates the bug (although the test passes because this PR fixes the bug).
The fix is to check to see if the `secret` is a string OR a buffer. Perhaps a better solution is to check to see if `secret` is a callback.
The error you will see is of the form:
```
TypeError: object is not a function
at async.parallel.revoked …
```

Fix for 'Buffer' secret with new multitenancy callback 

---

lib/index.js
package.json
test/jwt.test.js

Depends on https://github.com/auth0/node-jsonwebtoken/pull/89
This allows the secret callback to inspect token headers (including `kid`), which is needed when fetching keys from a JWKS and supporting key rotation.

Optionally pass token headers to secret callback.

---

README.md

When I was using this, I couldn't figure out how to exclude wildcard routes until I found this issue: https://github.com/auth0/express-jwt/issues/53. I also didn't realize the `unless()` functionality was based on another module with more options than what is currently described, so I added a line in a README to document that.

Expand on what is possible with path param for unless()

---

README.md

- Updated responses to Express 4.x format (`res.sendStatus(status)` [(ref)](http://expressjs.com/api.html#res.sendStatus) instead of `res.send(status)`, `res.status(500).send("...")` instead of `res.send(status, "...")`
- Fixed a small typo (pat -> path)

Update status responses to Express 4.x format

---

lib/index.js
package.json

Hey guys
I noticed you were using the entire lodash library and are only using a single function.
So I propose we use the `lodash.set` module, which is an officially lodash maintained NPM package.
(https://www.npmjs.com/package/lodash.set)
I've also contemplated just upgrading the whole lodash package to `^4.2.1`, that way this package can use an existing project's lodash `4.x.x` package since they flattened the node_modules structure in one of the npm versions.
Let me know what you think!

More lightweight dependency

---

package.json

Hi, 
We recently updated express-jwt in our platform and we had some issues with the latest version in conjunction with our test suite (in particular mochajs and supertest). 
After some digging we realized the issue was inside the async library. In particular when inside the ```async.waterfall``` the ```async.setImmediate``` method is called. 
We found this issue https://github.com/caolan/async/issues/696. 
So, we decided to update async to the latest version and give it a try. Everything worked again.

Updated package.json. async ^1.5.0

---

lib/index.js
test/jwt.test.js

This is to open the discussion, it's OK to have a property used for bypassing token checks. It turns out to be very useful on our case. 
~~However I think (and it's purely based on our use case) that whenever a token is provided the middleware should fail if the token is no longer valid. I don't see the reason why you will by-pass the token error.~~
~~I understand that this could be a major breaking change, it could be added as an option too.~~
*UPDATE*: Instead of changing the default behavior, I've introduced a new option `alwaysThrowOnExpiredToken` which forces the app to throw an exception on expired tokens even when credentials are not required.

Add option to force throw on expired tokens even when credentials are not required

---

lib/index.js

One step easier for all of us to access UnauthorizedError just like in the other auth0 libraries
``` javascript
require('express-jwt').UnauthorizedError
require('jsonwebtoken').JsonWebTokenError
```

UnauthorizedError exports directly from the module

---

lib/errors/UnauthorizedError.js
test/jwt.test.js

express-jwt's stack traces don't include error message.
Using the library I was getting error messages like this:
Error
at /home/mike/projects/cloned/express-jwt/lib/index.js:101:22
at /home/mike/projects/cloned/express-jwt/node_modules/jsonwebtoken/index.js:54:18
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
Error.captureStackTrace uses the type and the message during the
creation of the stack trace. This commit calls Error.captureStackTrace
after setting name and message so that the stack trace includes the
description like so:
UnauthorizedError: invalid signature
at /home/mike/projects/cloned/express-jwt/lib/index.js:101:22
at /home/mike/projects/cloned/express-jwt/node_modules/jsonwebtoken/index.js:54:18
at …

Ensure proper error messages end up in stack trace

---

README.md
lib/index.js
test/jwt.test.js

According to the Express 4.0 [docs](http://expressjs.com/en/api.html#res.locals), the recommended place to put request scoped data is on `res.locals`.
This pull request adds a `resultProperty` option which when set will override the default `req.user` with the passed in property path on the result object. If both `requestProperty` and `resultProperty` are set, then `requestProperty` is ignored.
```javascript
jwt({ secret: publicKey, resultProperty: 'locals.user' });
```
This change seems sensible to me because it allows support for using `res.locals` while maintaining backwards compatibility.

Add option to attach user object to result

---

README.md
lib/index.js
package-lock.json
package.json

Signed-off-by: Ryan McQuen <RyanMcQuen@stockx.com>
Closes security vulnerability by adopting main lodash package, outlined here:
https://github.com/auth0/express-jwt/issues/271
- [GitHub Issue/PR number addressed or fixed](https://github.com/auth0/express-jwt/issues/271)

Fix prototype pollution vulnerability.

---

README.md

Add example on how to enable jwt for specific path, as compared to _disabling_ for a specific path which was the only example shown before.
Some context as to why I feel this would help. People are doing various more or less miss-guided workarounds for this across the interwebs. See some examples here:
* https://stackoverflow.com/questions/31496439/express-jwt-not-respecting-unprotected-paths
* https://stackoverflow.com/questions/47670921/express-jwt-exclude-certain-routes
* https://medium.com/javascript-in-plain-english/verifying-json-web-tokens-with-express-jwt-1ae147aa9bd3

Add example on how to enable jwt for specific path

---

src/index.ts
test/UnauthorizedError.test.ts
test/jwt.test.ts
test/multitenancy.test.ts
test/revocation.test.ts
test/string_token.test.ts
tsconfig.json

Fixed build error when not using the `esModuleInterop` flag
> node_modules/express-jwt/dist/index.d.ts:3:8 - error TS1259: Module '"/home/runner/work/my-project/node_modules/@types/express-unless/index"' can only be default-imported using the 'esModuleInterop' flag
> 
> 3 import expressUnless from 'express-unless';
>          ~~~~~~~~~~~~~
> 
>   node_modules/@types/express-unless/index.d.ts:30:1
>     30 export = unless;
>        ~~~~~~~~~~~~~~~~
>     This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
Fixes https://github.com/auth0/express-jwt/issues/291

Fix tsc build error for express-unless

---

README.md

Fixed misspelled word in README
Github Issue: https://github.com/auth0/express-jwt/issues/299

README: Fix misspelled word in readme

---

src/index.ts

It makes it possible to import `Params` type of the middleware function
#308

feat: export middleware options type. closes #308

---

src/index.ts

A [PR was recently merged](https://github.com/auth0/node-jwks-rsa/pull/329) to auth0/node-jwks-rsa that changed the type of `GetVerificationKey`, which breaks the interaction with express-jwt. This PR updates the type here to match the change there.
- [Issue that led to node-jwks-rsa change](https://github.com/auth0/node-jwks-rsa/issues/328
- [PR of the actual change](https://github.com/auth0/node-jwks-rsa/pull/329)
- Fixes #304 
None, does this need a test?

update GetVerificationKey type to match node-jwks-rsa

---

test/jwt.test.ts

The failure tests 'should throw error when signature is wrong' test case was incorrectly building a test input in two ways:
1. The payload content was encoded as a base64 string, which in this case added special padding chars ('='). These chars do not comply with the JWT specification, and are expected to not be present by downstreams that perform the token validation and verification. This change fixes the test token to remove the padding chars, the same way this is done in the downstream ([code pointer](https://github.com/auth0/node-jws/blob/b9fb8d30e9c009ade6379f308590f1b0703eefc3/lib/sign-stream.js#L13)).
2. Also, the payload content was being built from a string literal, meant to represent a stringified POJO (aka a JSON string), which was ill-formed (missing quotes). This change …

Modify tests to actually exercise wrong signature case by removing base64 padding chars from test token

---

package-lock.json
package.json
src/index.ts

This pull request includes changes to the `expressjwt` middleware function in `src/index.ts` to improve type safety and ensure proper function termination.
Type safety improvements:
* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L119-R119): Added a return type of `Promise<void>` to the `middleware` function to explicitly specify that it returns a promise.
Function termination:
* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L128-R129): Modified the `setImmediate` call to include a `return` statement to ensure the function terminates properly after calling `setImmediate`.

Fix signature
